version: "3.8"
services:
  blacklists-misp:
    image: blacklists-misp:latest
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 8000:80
     volumes:
      - ./data:/app/data
      